# ----------------------------
# Makefile Options
# ----------------------------

NAME = TINESEMU
DESCRIPTION = "NES Emulator"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)